# SubNav
menu:
  #关于我: /2014/aboutme/
  #友链: /2014/friends/
subnav:
  github: "https://github.com/ingchang"
  #weibo: "https://weibo.com/2504173754/profile?topnav=1&wvr=6&is_all=1"
  email: "mailto:ingchang@qq.com"
  #sf: "https://segmentfault.com/u/tryonce"

description: 旺上加旺

# SEO
seo_keywords: hexo,个人博客,blog
seo_description: ingchang的个人博客

favicon: /favicon.ico

#你的头像url
avatar: http://img5a.flixcart.com/image/poster/7/u/v/everything-will-be-ok-pm1084-400x400-imae39guuqwmhsg4.jpeg

# 首页左侧边栏背景图片
# 可配置多个 随机挑选一张
leftBackground:
  - https://ws3.sinaimg.cn/large/006tKfTcly1fsulzlvofnj30af0k5jvu.jpg
  - https://ws2.sinaimg.cn/large/006tNbRwly1fwl2alhqibj31kw2dcu0y.jpg
  - https://ws3.sinaimg.cn/large/006tNbRwly1fwl2dentnvj31kw2dc1l2.jpg
  - https://ws4.sinaimg.cn/large/006tNbRwly1fwl2dqawiej31kw2d8x6p.jpg

# 展示更新时间
display_updated: true

# 文章页的关于转载链接
#copyright_url: https://888.com/index.html

# 底部的备案信息等
copyright_date: 2013-2018
beian_info: 

# Online contact
daovoice: true
daovoice_app_id: 123456 #输入app_id

# Data statistics
baidu_analytics: true
baidu_analytics_code: awwssw1snsnsnn1ndndnndnd99j

#Comments
gitalk: true
gitalk_clientID: 8888a8888
gitalk_clientSecret: 8888886666666
gitalk_repo: ingchang.github.io
gitalk_owner: admin
gitalk_admin: admin
# 是否启用评论框的全屏遮罩效果
gitalk_distractionFreeMode: false

