# SubNav
menu:
  #关于我: /2014/aboutme/
  #友链: /2014/friends/
subnav:
  github: "https://github.com/ingchang"
  #weibo: "https://weibo.com/2504173754/profile?topnav=1&wvr=6&is_all=1"
  email: "mailto:ingchang@qq.com"
  #sf: "https://segmentfault.com/u/tryonce"

description: 旺上加旺

# SEO
seo_keywords: hexo,个人博客,blog
seo_description: ingchang的个人博客

favicon: /favicon.ico

#你的头像url
avatar: https://cdn.nlark.com/yuque/0/2019/jpeg/264540/1550037746777-3e4d247a-5e9e-4058-918e-cfc0534ab2ac.jpeg

# 首页左侧边栏背景图片
# 可配置多个 随机挑选一张
leftBackground:
  - https://cdn.nlark.com/yuque/0/2019/jpeg/264540/1560419991920-73a9b0e1-f6e1-4e96-bc82-19b716dcef34.jpeg
  - https://cdn.nlark.com/yuque/0/2019/jpeg/264540/1560419998125-43525ef5-8d9a-4073-8f8d-15c431610411.jpeg
  - https://cdn.nlark.com/yuque/0/2019/jpeg/264540/1560420000536-9077486c-8ca8-461e-8ff8-c3e312d2280a.jpeg
  - https://cdn.nlark.com/yuque/0/2019/jpeg/264540/1560420014128-6ff22aa3-1901-42e2-9e46-e864e6ad8eb4.jpeg

# 展示更新时间
display_updated: true

# 文章页的关于转载链接
#copyright_url: https://888.com/index.html

# 底部的备案信息等
copyright_date: 2013-2018
beian_info: 

# Online contact
daovoice: true
daovoice_app_id: 123456 #输入app_id

# Data statistics
baidu_analytics: true
baidu_analytics_code: awwssw1snsnsnn1ndndnndnd99j

#Comments
gitalk: true
gitalk_clientID: 8888a8888
gitalk_clientSecret: 8888886666666
gitalk_repo: ingchang.github.io
gitalk_owner: admin
gitalk_admin: admin
# 是否启用评论框的全屏遮罩效果
gitalk_distractionFreeMode: false

